#!/bin/bash -x

###############################################################################
#
# Copyright 2022 NVIDIA Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
###############################################################################
DISTRO=anolis
DISTRO_VERSION=8.6
DOCA_VERSION=2.2.0
BSP_VERSION=4.2.1-12867
MLNX_OFED_VERSION=23.07-0.5.0.0
WDIR=${WDIR:-/tmp}

# Execute command w/ echo and exit if it fail
ex()
{
	echo "$@"
	if ! "$@"; then
		printf "\nFailed executing $@\n\n"
		exit 1
	fi
}

dnf update -y
dnf install -y epel-release

#Kernel upgrade
ex yum-config-manager --nogpgcheck --add-repo https://mirrors.openanolis.cn/anolis/8.6/Experimental/aarch64/os/
#Probably only 1 of the 2 is needed (above or below)
echo -e "[Experimental] \n\
name=AnolisOS-8.6 - Experimental \n\
baseurl=http://mirrors.openanolis.cn/anolis/8.6/Experimental/aarch64/os \n\
enabled=1 \n\
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ANOLIS \n\
gpgcheck=1" > /etc/yum.repos.d/AnolisOS-Experimental.repo

yum update --nogpgcheck -y kernel-core kernel kernel-modules kernel-devel kernel-headers

kernel=`/bin/ls -1tr /lib/modules | tail -1`

echo -e "[kubernetes] \n\
name=Kubernetes \n\
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-aarch64 \n\
enabled=1 \n\
gpgcheck=1 \n\
gpgkey=https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg \n\
exclude=kubelet kubeadm kubectl kubernetes-cni" > /etc/yum.repos.d/kubernetes.repo

dnf install -y --disableexcludes=kubernetes \
	rpm-build rpm-sign automake meson cmake gcc-c++ \
	bc bison flex pesign rsync patchutils git annobin intltool \
	groff kernel-rpm-macros libtool desktop-file-utils jq wget \
	systemd lm_sensors-sensord openssh-server acpid irqbalance unbound rasdaemon \
	cryptsetup lvm2 device-mapper-persistent-data ltrace lsof unzip sysstat nvme-cli \
	usbutils kexec-tools nfs-utils dracut-tools dracut-network dracut-squash iproute-tc sudo parted passwd \
	network-scripts NetworkManager NetworkManager-ovs NetworkManager-config-server tcpdump \
	libarchive libreswan rsyslog system-lsb-core time vim numactl libiscsi \
	perl-Fedora-VSP perl-generators edac-util dmidecode ipmitool \
	glib2-devel python3-devel elfutils-devel binutils-devel pciutils-devel openssl-devel \
	libnl3-devel selinux-policy-devel numactl-devel unbound-devel libpcap-devel tcl-devel \
	valgrind-devel iptables-devel libdb-devel libmnl-devel libcap-ng-devel systemd-devel \
	grubby grub2-efi-aa64 shim-aa64 efibootmgr re2c watchdog libmd libmd-devel libbsd libbsd-devel

update-alternatives --install /usr/bin/python python /usr/bin/python3.6 1

dnf install -y --disableexcludes=kubernetes \
    kubelet-1.25.3 kubernetes-cni-1.1.1 cri-tools
dnf install -y rpm-build rpm-sign automake meson cmake gcc-c++

mkdir -p $WDIR
cd $WDIR

# Build and install MLNX_OFED drivers
ex wget --quiet https://linux.mellanox.com/public/repo/doca/${DOCA_VERSION}/extras/mlnx_ofed/${MLNX_OFED_VERSION}/MLNX_OFED_SRC-${MLNX_OFED_VERSION}.tgz
ex tar xzf MLNX_OFED_SRC-${MLNX_OFED_VERSION}.tgz
ex MLNX_OFED_SRC-${MLNX_OFED_VERSION}/install.pl -k $kernel --kernel-extra-args '--with-sf-cfg-drv --without-xdp --without-odp' --kernel-only --disable-kmp

# Build and install BlueField SoC drivers
ex wget --quiet -r -np -nH --cut-dirs=3 -R "index.html*" https://linux.mellanox.com/public/repo/doca/${DOCA_VERSION}/extras/SRPMS/
mkdir -p ${WDIR}/${DOCA_VERSION}/extras/{SPECS,RPMS,SOURCES,BUILD}

for p in ${WDIR}/${DOCA_VERSION}/extras/SRPMS/*.src.rpm
do
	case $p in
		*rshim* | *libpka* | *mlx-OpenIPMI* | *mlxbf-bootctl*)
			continue
			;;
	esac
	ex rpmbuild --rebuild -D "debug_package %{nil}" -D "KVERSION $kernel" --define "KMP 0" --define "_topdir ${WDIR}/${DOCA_VERSION}/extras" $p
done

ex rpm -ivh --force ${WDIR}/${DOCA_VERSION}/extras/RPMS/aarch64/*.rpm

yum-config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
yum install -y --enablerepo=extras --nogpgcheck docker-ce docker-ce-cli container-selinux containerd.io
systemctl enable docker

ex yum-config-manager --nogpgcheck --add-repo https://linux.mellanox.com/public/repo/doca/${DOCA_VERSION}/anolis8.6/aarch64/

ex yum install --nogpgcheck -y doca-runtime-user doca-sdk-user doca-tools

ex rpm -ihv --force /root/workspace/mlxbf-bootimages-*.aarch64.rpm

/usr/sbin/update-pciids || true

sed -i -e "s/*/Anolis_8.6/" /etc/mlnx-release
sed -i -e "s/signed/@IMAGE_TYPE@@CUSTOM_VERSION@/" /etc/mlnx-release

ex /root/workspace/create_bfb -k $kernel
